# Generated by Django 4.2 on 2024-05-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bojovnice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlavni_jmeno', models.CharField(max_length=50)),
                ('obdobi', models.CharField(max_length=50)),
                ('uzemi', models.CharField(max_length=50)),
                ('popis', models.TextField(max_length=100)),
                ('pribeh', models.TextField(max_length=2000)),
            ],
            options={
                'ordering': ('stoleti__pk',),
            },
        ),
        migrations.CreateModel(
            name='Staty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('nazev',),
            },
        ),
        migrations.CreateModel(
            name='Stoleti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VsechnaJmena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('bojovnice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bojovnice_app.bojovnice')),
            ],
            options={
                'ordering': ('jmeno',),
            },
        ),
        migrations.CreateModel(
            name='SkupinyBojovnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('popis', models.TextField(max_length=5000)),
                ('stat', models.ManyToManyField(blank=True, to='bojovnice_app.staty')),
            ],
        ),
        migrations.AddField(
            model_name='bojovnice',
            name='stat',
            field=models.ManyToManyField(to='bojovnice_app.staty'),
        ),
        migrations.AddField(
            model_name='bojovnice',
            name='stoleti',
            field=models.ManyToManyField(to='bojovnice_app.stoleti'),
        ),
    ]
