# Generated by Django 4.2 on 2024-06-18 11:28

import bojovnice_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bojovnice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('obdobi', models.CharField(max_length=50)),
                ('uzemi', models.CharField(max_length=50)),
                ('popis', models.TextField(max_length=100)),
                ('pribeh', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Bojovnice',
                'ordering': ('jmeno',),
            },
            bases=(models.Model, bojovnice_app.models.Data),
        ),
        migrations.CreateModel(
            name='Staty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('polygon_text', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Státy',
                'ordering': ('nazev',),
            },
            bases=(models.Model, bojovnice_app.models.Data),
        ),
        migrations.CreateModel(
            name='Stoleti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Století',
            },
            bases=(models.Model, bojovnice_app.models.Data),
        ),
        migrations.CreateModel(
            name='VsechnaJmena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('hlavni_jmeno', models.BooleanField(default=False)),
                ('bojovnice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bojovnice_app.bojovnice')),
            ],
            options={
                'verbose_name_plural': 'Všechna jména',
                'ordering': ('bojovnice', 'jmeno'),
            },
        ),
        migrations.CreateModel(
            name='SkupinyBojovnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('popis', models.TextField(max_length=5000)),
                ('bojovnice', models.ManyToManyField(blank=True, to='bojovnice_app.bojovnice')),
                ('stat', models.ManyToManyField(blank=True, to='bojovnice_app.staty')),
                ('stoleti', models.ManyToManyField(blank=True, to='bojovnice_app.stoleti')),
            ],
            options={
                'verbose_name_plural': 'Skupiny bojovnic',
                'ordering': ('jmeno',),
            },
            bases=(models.Model, bojovnice_app.models.Data),
        ),
        migrations.CreateModel(
            name='BojovniceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('bojovnice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bojovnice_app.bojovnice')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bojovnice_app.staty')),
            ],
            options={
                'verbose_name_plural': 'BojovniceStaty M2M-tab',
                'ordering': ('bojovnice', 'stat'),
            },
        ),
        migrations.AddField(
            model_name='bojovnice',
            name='stat',
            field=models.ManyToManyField(through='bojovnice_app.BojovniceStat', to='bojovnice_app.staty'),
        ),
        migrations.AddField(
            model_name='bojovnice',
            name='stoleti',
            field=models.ManyToManyField(to='bojovnice_app.stoleti'),
        ),
    ]
