# Generated by Django 4.2 on 2024-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bojovnice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bojovnice',
            options={'ordering': ('hlavni_jmeno',)},
        ),
        migrations.AddField(
            model_name='skupinybojovnic',
            name='stoleti',
            field=models.ManyToManyField(blank=True, to='bojovnice_app.stoleti'),
        ),
    ]
