# Generated by Django 4.2 on 2024-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bojovnice_app', '0002_alter_bojovnice_options_skupinybojovnic_stoleti'),
    ]

    operations = [
        migrations.AddField(
            model_name='skupinybojovnic',
            name='bojovnice',
            field=models.ManyToManyField(blank=True, to='bojovnice_app.bojovnice'),
        ),
    ]
