# Generated by Django 4.2 on 2024-06-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bojovnice_app', '0003_skupinybojovnic_bojovnice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bojovnice',
            options={'ordering': ('jmeno',), 'verbose_name_plural': 'Bojovnice'},
        ),
        migrations.AlterModelOptions(
            name='skupinybojovnic',
            options={'ordering': ('jmeno',), 'verbose_name_plural': 'Skupiny bojovnic'},
        ),
        migrations.AlterModelOptions(
            name='staty',
            options={'ordering': ('nazev',), 'verbose_name_plural': 'Státy'},
        ),
        migrations.AlterModelOptions(
            name='stoleti',
            options={'verbose_name_plural': 'Století'},
        ),
        migrations.AlterModelOptions(
            name='vsechnajmena',
            options={'ordering': ('jmeno',), 'verbose_name_plural': 'Všechna jména'},
        ),
        migrations.RenameField(
            model_name='bojovnice',
            old_name='hlavni_jmeno',
            new_name='jmeno',
        ),
        migrations.RenameField(
            model_name='skupinybojovnic',
            old_name='nazev',
            new_name='jmeno',
        ),
    ]
