# Generated by Django 4.2 on 2024-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bojovnice_app', '0004_alter_bojovnice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsechnajmena',
            name='hlavni_jmeno',
            field=models.BooleanField(default=False),
        ),
    ]
